//
//  RecipeModel.swift
//  Foodtracker 0.01
//
//  Created by Admin on 02.02.17.
//  Copyright © 2017 Admin. All rights reserved.
//

import Foundation

let CaesarSalad = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "caesar1"), pictureForRecipeVC: #imageLiteral(resourceName: "caesar0"), text: "Ingredients:\nChicken fillet - 150 Grams\nTomato - 1\nEgg - 2 pcs\nWhite bread - 2 slices\nLettuce - 4-5 Pieces\nOlive oil - 2 tbsp. spoons\nLemon juice - 1 tbsp. a spoon\nMustard - To taste\n\n\nSesame seeds - 2 pinches1.Prepare all the ingredients. Boil hard boiled eggs.\n2. Chicken fillet cut into small size plate thickness of 5-6 mm. and fry in a small amount of vegetable oil until golden brown. Ideal if you roast them on the grill.\n3. The bread cut into small cubes and drain in the oven or microwave.\n4. Tomato peel and cut not thick slices.\n5. Assemble the salad. At the bottom of the dish, place the washed lettuce leaves, put tomatoes, croutons, sliced ​​eggs and chicken.\n6. Prepare the filling: Mix in a small kremanke freshly squeezed lemon juice, mustard and a little olive oil. Pour the finished mixture of lettuce, sprinkle with sesame seeds. Though they are not included in the classic version of <<Caesar>> salad, very well with vegetables and salad lend piquancy. Serve a salad as an appetizer before the main course or as a main dish. Bon Appetit!", name: "Caesar salad",  ingredients: [chickenFillet, tomato, egg, whiteBread, lettuce, oliveOil, lemonJuice, mustard, sesameSeeds])

let buritto = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "buritto1"), pictureForRecipeVC: #imageLiteral(resourceName: "buritto0"), text: "Ingredients:\nground beef - 500 Grams\ntortillas - 8 Pieces\nsunflower oil - 2 tbsp. spoons\nbeans - 400 grams (fried)\nsalad - 1 Each\ntomatoes - 5 Pieces\ngreen onions - 1 Each\ncheddar cheese - 200 grams\nonions - 2 pieces\n2 teaspoons - chilli powder\ncumin - 1 teaspoon\nsalt - 1 Thing (to taste)\npepper - 1 Thing (to taste)\n\n\nFry the onions over medium heat for 10 minutes. At this time, spice mix into paste with a little water.\nAdd the paste to the onions and cook for 5 minutes.\nAdd mince.\nAdd the beans and season with salt and pepper to taste.\nWhen the meat is ready, chopped tomato, lettuce and onions.\nRefill filling into tortillas.\nFold bore as shown in the picture.\nPuts drills in shape.\nCover with foil and bake for 40 minutes.", name: "Buritto", ingredients: [groundBeef, tortillas, sunflowerOil, beans, lettuce, tomato, greenOnions, cheddarCheese, onions, chilliPowder, cumin, salt, redPepper])

let shrimpPasta = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "shrimp pasta1"), pictureForRecipeVC: #imageLiteral(resourceName: "shrimp pasta0"), text: "¾pound gemelli, fusilli, or other short pasta\n2 tablespoons unsalted butter\n2 leeks (white and light green parts only), halved lengthwise then crosswise\nkosher salt and black pepper\n1 pound peeled and deveined medium shrimp (raw)\nfinely grated zest of 1 lemon\n¾ cup heavy cream\n10 ounces baby spinach (about 12 cups)\n\nDIRECTIONS\nCook the pasta according to the package directions; drain and return it to the pot.\nMeanwhile, heat the butter in a large skillet over medium heat. Add the leeks, ½ teaspoon salt, and ¼ teaspoon pepper and cook, stirring occasionally, until the leeks have softened, 3 to 5 minutes.\nAdd the shrimp and lemon zest and cook, tossing frequently, until the shrimp is opaque throughout, 4 to 5 minutes more.\nAdd the cream and ½ teaspoon salt to the pasta in the pot and cook over medium heat, stirring, until slightly thickened, 1 to 2 minutes. Add the shrimp mixture and the spinach and toss to combine.", name: "Shrimp, Leek, and Spinach Pasta", ingredients: [shortPasta, butter, salt, blackPepper, shrimps, lemon, heavyCream, babySpinach])

let shrimpWithTomatoesAndOlives = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "shrimp with tomatoes and olives1"), pictureForRecipeVC: #imageLiteral(resourceName: "shrimp with tomatoes and olives0"), text: "INGREDIENTS\n\n\n1 10-ounce box couscous (1⅓ cups)\n1 tablespoon olive oil\n1 small onion, chopped\n1 28-ounce can diced tomatoes, drained\n¾ cup pitted green olives\n½ cup dry white wine (such as Sauvignon Blanc)\nkosher salt and pepper\n1 pound medium shrimp, peeled and deveined\n\n\nDIRECTIONS\n\n\nCook the couscous according to the package directions.\nMeanwhile, heat the oil in a large saucepan over medium-high heat. Add the onion and cook, stirring occasionally, for 4 minutes.\nAdd the tomatoes, olives, wine, ½ teaspoon salt, and ¼ teaspoon pepper. Simmer, stirring occasionally, until slightly thickened, 4 to 6 minutes.\nAdd the shrimp and cover. Cook until the shrimp are cooked through, 3 to 5 minutes. Serve with the couscous.", name: "Shrimp With Tomatoes and Olives", ingredients: [couscous, oliveOil, onions, tomato, greenOlives, dryWhiteWine, salt, blackPepper, shrimps])

let omelet = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "Omelet1"), pictureForRecipeVC: #imageLiteral(resourceName: "Omelet0"), text: "Whisk the eggs with a mixer. First, at low speed, then - at a maximum. Add milk, salt, spices. Once again a good beat. Heat the pan well. Brush with vegetable oil. Pour beaten egg mass. Cook over medium heat for 2-3 minutes. Then, set the low heat, cover and cook for another 3-4 minutes to harden. The finished dish serve with chopped herbs.", name: "Omelet", ingredients: [milk, butter, salt, egg, flour])

let spicySalmon = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "spicy salmon1"), pictureForRecipeVC: #imageLiteral(resourceName: "spicy salmon0"), text: "INGREDIENTS\n\n\n1cup long-grain white rice\n2tablespoons honey\n1tablespoon soy sauce\n¼teaspoon crushed red pepper\n4 6-ounce skinless salmon fillets\n1pound baby bok choy\n\n\nDIRECTIONS\n\n\nCook the rice according to the package directions.\nMeanwhile, combine the honey, soy sauce, and red pepper. On a foil-lined rimmed baking sheet, broil the salmon fillets until opaque throughout, 8 to 10 minutes, basting with the honey mixture during the last 3 minutes.\nSteam baby bok choy (cut into quarters) until tender, 8 to 10 minutes. Serve with the salmon and rice.", name: "Spicy Salmon With Bok Choy and Rice", ingredients: [longgrainRice, crushedRedPepper, salmonFillet, babyBokChoy, soySauce, honey])

let salmonWithCreamyCucumberFennelSalad = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "salmon-creamy-cucumber1"), pictureForRecipeVC: #imageLiteral(resourceName: "salmon-creamy-cucumber0"), text: "INGREDIENTS  \n\n\n4 6-ounce pieces skinless salmon fillet 1 tablespoon olive oil \n¼ teaspoon cayenne pepper kosher salt and black pepper \n1 lemon, thinly sliced \n½ cup plain low-fat Greek yogurt \n1 tablespoon cider vinegar \n1 fennel bulb, cored and thinly sliced, plus 2 tablespoons chopped fennel fronds \n½ English cucumber, thinly sliced \nrye bread, for serving \n\n\nDIRECTIONS \n\n\nHeat oven to 400° F. Rub the salmon with the oil and place on a rimmed baking sheet. Season with the cayenne and ¼ teaspoon each salt and black pepper. Top with the lemon slices and bake until opaque throughout, 8 to 12 minutes. Meanwhile, whisk together the yogurt, vinegar, and ¼ teaspoon each salt and black pepper in a large bowl. Add the fennel, fennel fronds, and cucumber and toss to coat. Serve the salmon with the cucumber-fennel salad and bread.", name: "Salmon With Creamy Cucumber-Fennel Salad", ingredients: [salmonFillet, oliveOil, cayennePepper, salt, blackPepper, lemon, greekYogurt, ciderVinegar, fennel, cucumbers, ryeBread])

let chickenZucchiniAndProscutto = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "chicken-zucchini-prosciutto1"), pictureForRecipeVC: #imageLiteral(resourceName: "chicken-zucchini-prosciutto0"), text: "INGREDIENTS \n\n\n4 boneless, skinless chicken breasts \n1/2 teaspoon kosher salt \n1/2 teaspoon black pepper \n2 tablespoons olive oil \n1/4 pound (about 8 slices) prosciutto \n3 small zucchini, thinly sliced into half-moons \n1 clove garlic, thinly sliced \n1 lemon \n\n\nDIRECTIONS \n\n\nHeat oven to 400° F. Season the chicken with ¼ teaspoon each of the salt and pepper. Heat 1 tablespoon of the oil in a large ovenproof skillet over medium-high heat. Cook the chicken for 2 minutes per side. Transfer the chicken to the oven and roast for 8 minutes. Meanwhile, in a second skillet, over medium heat, heat the remaining oil. Cook the prosciutto until crisp, 1 to 2 minutes per side. Transfer to a plate. Add the zucchini, garlic, and remaining salt and pepper to the skillet and cook until tender, about 3 minutes. Add the prosciutto and zucchini mixture to the skillet with the chicken, squeeze the lemon over the top, and toss. Divide among the plates.", name: "Chicken, Zucchini, and Prosciutto", ingredients: [chickenFillet, salt, blackPepper, oliveOil, prosciutto, zucchini, garlic, lemon])

let bakedPecorinoChicken = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "chicken-pecorino1"), pictureForRecipeVC: #imageLiteral(resourceName: "chicken-pecorino0"), text: "Heat oven to 400° F. In a food processor, pulse the bread until coarse crumbs form (you should have about 2 cups). Add the pecorino, butter, ½ teaspoon salt, and ¼ teaspoon pepper and pulse once or twice to moisten. Place the chicken in an 8-inch baking dish; season with ½ teaspoon salt and ¼ teaspoon pepper and sprinkle with the bread crumb mixture. Cover with foil and bake until cooked through, 15 to 20 minutes. Uncover and bake until crumbs are golden, 3 to 5 minutes. Meanwhile, heat the oil in a large skillet over medium-high heat. Add the chard, ½ teaspoon salt, and ¼ teaspoon pepper. Cook, tossing, until tender, 3 to 4 minutes. Serve with the chicken.", name: "Baked Pecorino Chicken", ingredients: [whiteBread, salt, blackPepper, chickenFillet, sunflowerOil, chard])

let chickenCurryInAHurry = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "chicken-curry_1"), pictureForRecipeVC: #imageLiteral(resourceName: "chicken-curry_0"), text: "INGREDIENTS \n\n\n1 cup white rice 1 \n1/2 tablespoons olive oil 1 small yellow onion, thinly sliced 2 teaspoons curry powder \n1/2 cup plain yogurt \n3/4 cup heavy cream \n1/2 teaspoon kosher salt \n1/4 teaspoon black pepper 1 \n14.5-ounce can diced tomatoes, drained (optional) meat from 1 rotisserie chicken, sliced or shredded \n1/4 cup fresh cilantro leaves, roughly chopped \n\n\nDIRECTIONS \n\n\nCook the rice according to the package directions. Heat the oil in a skillet over medium-low heat. Add the onion and cook, stirring occasionally, for 7 minutes. Sprinkle with the curry powder and cook, stirring, for 1 minute. Add the yogurt and cream and simmer gently for 3 minutes. Stir in the salt, pepper, and tomatoes (if desired). Remove from heat. Divide the rice and chicken among individual bowls, spoon the sauce over the top, and sprinkle with the cilantro.", name: "Chicken Curry in a Hurry", ingredients: [longgrainRice, oliveOil, yellowOnion, curryPowder, plainYogurt, heavyCream, salt, blackPepper, tomato, chickenFillet, cilantro])

let pastaWithTurkeyAndBroccoli = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "pasta-turkey-broccoli1"), pictureForRecipeVC: #imageLiteral(resourceName: "pasta-turkey-broccoli0"), text: "INGREDIENTS \n\n\n¾ pound orecchiette \n2 cups broccoli florets \n3 tablespoons olive oil \n1 pound ground turkey \n2 cloves garlic, chopped \n1 teaspoon fennel seed \n½ teaspoon crushed red pepper \nkosher salt \nParmesan, for serving \n\n\nDIRECTIONS \n\n\nCook the pasta according to the package directions, adding the broccoli during the last minute. Drain and return the pasta and broccoli to the pot. Meanwhile, heat 1 tablespoon of the oil in a large skillet over medium-high heat. Add the turkey, garlic, fennel seed, and red pepper and cook, breaking up the meat with a spoon, until browned, 3 to 5 minutes; season with ½ teaspoon salt. Toss the turkey mixture with the pasta and broccoli and the remaining 2 tablespoons of oil. Serve with Parmesan.", name: "Pasta With Turkey and Broccoli", ingredients: [orecchiette, broccoli, oliveOil, groundTurkey, garlic, fennelSeeds, crushedRedPepper, salt, parmesan])

let zucchiniAndBeanSaladWithBulgur = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "zucchini-bulgur1"), pictureForRecipeVC: #imageLiteral(resourceName: "zucchini-bulgur0"), text: "INGREDIENTS \n\n\n1/4 cup olive oil \n2 tablespoons red wine vinegar kosher salt and black pepper \n2 medium zucchini (about 1 pound), halved and thinly sliced \n1 15.5-ounce can kidney beans, rinsed \n1 small shallot, thinly sliced \n1/4 cup chopped salted roasted almonds \n1/4 cup chopped fresh dill \n1 cup bulgur \n1 cup goat cheese, crumbled (4 ounces) \n\n\nDIRECTIONS \n\n\nWhisk together the oil, vinegar, ¾ teaspoon salt, and ¼ teaspoon pepper in a large bowl. Add the zucchini, beans, shallot, almonds, and dill and toss to combine. Let stand, tossing occasionally, until the zucchini softens slightly, 10 to 15 minutes. Meanwhile, place the bulgur in a separate large heatproof bowl. Add 2 cups boiling water, cover, and let stand until tender, 12 to 15 minutes; drain. Serve the bulgur topped with the zucchini salad and sprinkled with the goat cheese.", name: "Zucchini and Bean Salad With Bulgur", ingredients: [oliveOil, redWineVinegar, salt, blackPepper, zucchini, kidneyBeans, shallot, almonds, dill, bulgur, goatCheese])

let wholegrainSpaghettiWithKaleAndTomatoes = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "spaghetti-garlic-kale1"), pictureForRecipeVC: #imageLiteral(resourceName: "spaghetti-garlic-kale0"), text: "INGREDIENTS 6 ounces whole-grain spaghetti 2 tablespoons olive oil 1 medium red onion, thinly sliced 2 cloves garlic, chopped kosher salt and black pepper 1 bunch kale, thick stems removed and leaves torn into bite-size pieces (about 8 cups) 2 pints grape tomatoes, halved 1/3 cup chopped roasted almonds 1/4 cup grated pecorino (1 ounce), plus more for serving DIRECTIONS Cook the pasta according to the package directions. Reserve ¼ cup of the cooking water; drain the pasta and return it to the pot. Meanwhile, heat the oil in a large skillet over medium-high heat. Add the onion, garlic, ¼ teaspoon salt, and ⅛ teaspoon pepper. Cook, stirring occasionally, until beginning to brown, 4 to 5 minutes. Add the kale and cook, tossing frequently, until tender, 2 to 3 minutes. Add the tomatoes and cook, tossing frequently, until the tomatoes begin to soften, 1 to 2 minutes more. Add the kale mixture, almonds, pecorino, and reserved cooking water to the pasta and toss to combine. Serve with additional pecorino.", name: "Whole-Grain Spaghetti With Kale and Tomatoes", ingredients: [wholegrainSpaghetti, oliveOil, redOnions, garlic, salt, blackPepper, kale, tomato, almonds, pecorino])

let southwesternBeef = Recipe(pictureForRecipesCVC: #imageLiteral(resourceName: "beef-chili-corn1"), pictureForRecipeVC: #imageLiteral(resourceName: "beef-chili-corn0"), text: "INGREDIENTS 1 tablespoon olive oil 2 carrots, chopped 1 onion, chopped 1 poblano or bell pepper, chopped 1/2 pound ground beef 2 tablespoons tomato paste 2 15-ounce cans black beans, rinsed 1 tablespoon chili powder kosher salt and black pepper 1/2 cup corn kernels (from 1 ear, or frozen and thawed) 1/2 cup grated Cheddar (2 ounces) 2 scallions, sliced DIRECTIONS Heat the oil in a large saucepan over medium-high heat. Add the carrots, onion, and poblano and cook, stirring, for 3 minutes. Add the beef and cook, breaking it up with a spoon, until no longer pink, 3 to 5 minutes. Add the tomato paste and cook, stirring, until it is slightly darkened, 1 minute. Stir in the beans, chili powder, 3 cups water, ½ teaspoon salt, and ¼ teaspoon pepper. Simmer over medium heat until the vegetables are tender, 8 to 10 minutes. Stir in the corn. Divide the chili among bowls and top with the Cheddar and scallions.", name: "Southwestern Beef Chili With Corn", ingredients: [oliveOil, carrots, onions, bellPepper, groundBeef, tomatoPaste, blackBeans, chilliPowder, salt, blackPepper, cornCernels, cheddarCheese, greenOnions])




let allRecipes = [omelet, CaesarSalad, buritto, shrimpPasta, shrimpWithTomatoesAndOlives, spicySalmon, salmonWithCreamyCucumberFennelSalad, chickenZucchiniAndProscutto, bakedPecorinoChicken, chickenCurryInAHurry, pastaWithTurkeyAndBroccoli, zucchiniAndBeanSaladWithBulgur, wholegrainSpaghettiWithKaleAndTomatoes]

var userRecipe = [Product]()

var recipesToShow = [Recipe]()
